//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string MAHS { get; set; }
        public string MAMH { get; set; }
        public string MAHK { get; set; }
        public string MANAM { get; set; }
        public string MALOAIDIEM { get; set; }
        public Nullable<decimal> DIEM1 { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOCKY HOCKY { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOAIDIEM LOAIDIEM { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
