//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH_NAMHOC
    {
        public string MAHS { get; set; }
        public string MANAM { get; set; }
        public string MALOP { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
