//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.HOCSINH_NAMHOC = new HashSet<HOCSINH_NAMHOC>();
            this.PHANCONG = new HashSet<PHANCONG>();
            this.THOIKHOABIEU = new HashSet<THOIKHOABIEU>();
        }
    
        public string MALOP { get; set; }
        public string TENLOP { get; set; }
        public string MAKHOI { get; set; }
        public Nullable<int> SISO { get; set; }
        public string MAGVCN { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCSINH_NAMHOC> HOCSINH_NAMHOC { get; set; }
        public virtual KHOI KHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEU { get; set; }
    }
}
