//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUHUYNH
    {
        public string MAHS { get; set; }
        public string HOTEN { get; set; }
        public string QUANHE { get; set; }
        public Nullable<int> NAMSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string NGHENGHIEP { get; set; }
        public string NOILAM { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
