//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLTRUONGC3Entities : DbContext
    {
        public QLTRUONGC3Entities()
            : base("name=QLTRUONGC3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIEM> DIEM { get; set; }
        public virtual DbSet<DIEMDANH> DIEMDANH { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIEN { get; set; }
        public virtual DbSet<HOCKY> HOCKY { get; set; }
        public virtual DbSet<HOCSINH> HOCSINH { get; set; }
        public virtual DbSet<HOCSINH_NAMHOC> HOCSINH_NAMHOC { get; set; }
        public virtual DbSet<KHOI> KHOI { get; set; }
        public virtual DbSet<LOAIDIEM> LOAIDIEM { get; set; }
        public virtual DbSet<LOP> LOP { get; set; }
        public virtual DbSet<MONHOC> MONHOC { get; set; }
        public virtual DbSet<NAMHOC> NAMHOC { get; set; }
        public virtual DbSet<PHANCONG> PHANCONG { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOC { get; set; }
        public virtual DbSet<PHUHUYNH> PHUHUYNH { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THOIKHOABIEU> THOIKHOABIEU { get; set; }
        public virtual DbSet<VW_GV_DiemDanhChuNhiem> VW_GV_DiemDanhChuNhiem { get; set; }
        public virtual DbSet<VW_GV_NhapDiem> VW_GV_NhapDiem { get; set; }
        public virtual DbSet<VW_GV_TKB> VW_GV_TKB { get; set; }
        public virtual DbSet<VW_GV_ThongTinVaLopCN> VW_GV_ThongTinVaLopCN { get; set; }
        public virtual DbSet<VW_GV_XemDiem> VW_GV_XemDiem { get; set; }
        public virtual DbSet<VW_HS_TrangChu> VW_HS_TrangChu { get; set; }
    
        [DbFunction("QLTRUONGC3Entities", "FN_ThongKe_SiSoTheoKhoi")]
        public virtual IQueryable<FN_ThongKe_SiSoTheoKhoi_Result> FN_ThongKe_SiSoTheoKhoi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_ThongKe_SiSoTheoKhoi_Result>("[QLTRUONGC3Entities].[FN_ThongKe_SiSoTheoKhoi]()");
        }
    
        [DbFunction("QLTRUONGC3Entities", "FN_ThongKeDiemDanh_HS")]
        public virtual IQueryable<FN_ThongKeDiemDanh_HS_Result> FN_ThongKeDiemDanh_HS(string mAHS, string mANAM, string mAHK)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_ThongKeDiemDanh_HS_Result>("[QLTRUONGC3Entities].[FN_ThongKeDiemDanh_HS](@MAHS, @MANAM, @MAHK)", mAHSParameter, mANAMParameter, mAHKParameter);
        }
    
        public virtual int PROC_TKB_THEM(string mALOP, string mAMH, string mAGV, string mANAM, string mAHK, Nullable<int> tHU, Nullable<int> tIET, string mAPHONG)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var mAGVParameter = mAGV != null ?
                new ObjectParameter("MAGV", mAGV) :
                new ObjectParameter("MAGV", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            var tHUParameter = tHU.HasValue ?
                new ObjectParameter("THU", tHU) :
                new ObjectParameter("THU", typeof(int));
    
            var tIETParameter = tIET.HasValue ?
                new ObjectParameter("TIET", tIET) :
                new ObjectParameter("TIET", typeof(int));
    
            var mAPHONGParameter = mAPHONG != null ?
                new ObjectParameter("MAPHONG", mAPHONG) :
                new ObjectParameter("MAPHONG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TKB_THEM", mALOPParameter, mAMHParameter, mAGVParameter, mANAMParameter, mAHKParameter, tHUParameter, tIETParameter, mAPHONGParameter);
        }
    
        public virtual ObjectResult<PROC_TKB_TIMKIEM_Result> PROC_TKB_TIMKIEM(string mAGV, string mALOP, Nullable<int> tHU, Nullable<int> tIET)
        {
            var mAGVParameter = mAGV != null ?
                new ObjectParameter("MAGV", mAGV) :
                new ObjectParameter("MAGV", typeof(string));
    
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tHUParameter = tHU.HasValue ?
                new ObjectParameter("THU", tHU) :
                new ObjectParameter("THU", typeof(int));
    
            var tIETParameter = tIET.HasValue ?
                new ObjectParameter("TIET", tIET) :
                new ObjectParameter("TIET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_TKB_TIMKIEM_Result>("PROC_TKB_TIMKIEM", mAGVParameter, mALOPParameter, tHUParameter, tIETParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_DiemDanh_CaNhan(string mAHS, string mANAM, string mAHK, Nullable<System.DateTime> nGAY, Nullable<int> tIET, string tRANGTHAI, string lYDOVANG)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            var nGAYParameter = nGAY.HasValue ?
                new ObjectParameter("NGAY", nGAY) :
                new ObjectParameter("NGAY", typeof(System.DateTime));
    
            var tIETParameter = tIET.HasValue ?
                new ObjectParameter("TIET", tIET) :
                new ObjectParameter("TIET", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI != null ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(string));
    
            var lYDOVANGParameter = lYDOVANG != null ?
                new ObjectParameter("LYDOVANG", lYDOVANG) :
                new ObjectParameter("LYDOVANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DiemDanh_CaNhan", mAHSParameter, mANAMParameter, mAHKParameter, nGAYParameter, tIETParameter, tRANGTHAIParameter, lYDOVANGParameter);
        }
    
        public virtual int SP_DiemDanh_HangLoat(string mALOP, string mANAM, string mAHK, Nullable<System.DateTime> nGAY, Nullable<int> tIET, string tRANGTHAI, string lYDOVANG)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            var nGAYParameter = nGAY.HasValue ?
                new ObjectParameter("NGAY", nGAY) :
                new ObjectParameter("NGAY", typeof(System.DateTime));
    
            var tIETParameter = tIET.HasValue ?
                new ObjectParameter("TIET", tIET) :
                new ObjectParameter("TIET", typeof(int));
    
            var tRANGTHAIParameter = tRANGTHAI != null ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(string));
    
            var lYDOVANGParameter = lYDOVANG != null ?
                new ObjectParameter("LYDOVANG", lYDOVANG) :
                new ObjectParameter("LYDOVANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DiemDanh_HangLoat", mALOPParameter, mANAMParameter, mAHKParameter, nGAYParameter, tIETParameter, tRANGTHAIParameter, lYDOVANGParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_GetBangDiemTongHop_Result> sp_GetBangDiemTongHop(string mAHS, string mANAM)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBangDiemTongHop_Result>("sp_GetBangDiemTongHop", mAHSParameter, mANAMParameter);
        }
    
        public virtual ObjectResult<sp_GetDanhSachHocSinhVaDiem_Result> sp_GetDanhSachHocSinhVaDiem(string mALOP, string mAMH, string mANAM, string mAHK)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDanhSachHocSinhVaDiem_Result>("sp_GetDanhSachHocSinhVaDiem", mALOPParameter, mAMHParameter, mANAMParameter, mAHKParameter);
        }
    
        public virtual ObjectResult<sp_GetDanhSachLop_Result> sp_GetDanhSachLop(string mANAM, string mAHK)
        {
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDanhSachLop_Result>("sp_GetDanhSachLop", mANAMParameter, mAHKParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_NhapDiem(string mAHS, string mAMH, string mAHK, string mANAM, string mALOAIDIEM, Nullable<decimal> dIEM, string gHICHU, ObjectParameter result, ObjectParameter message)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mALOAIDIEMParameter = mALOAIDIEM != null ?
                new ObjectParameter("MALOAIDIEM", mALOAIDIEM) :
                new ObjectParameter("MALOAIDIEM", typeof(string));
    
            var dIEMParameter = dIEM.HasValue ?
                new ObjectParameter("DIEM", dIEM) :
                new ObjectParameter("DIEM", typeof(decimal));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhapDiem", mAHSParameter, mAMHParameter, mAHKParameter, mANAMParameter, mALOAIDIEMParameter, dIEMParameter, gHICHUParameter, result, message);
        }
    
        public virtual ObjectResult<SP_NV5_FixLoiDangNhap_Result> SP_NV5_FixLoiDangNhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NV5_FixLoiDangNhap_Result>("SP_NV5_FixLoiDangNhap");
        }
    
        public virtual int SP_NV5_ThuHoiQuyenAdmin(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NV5_ThuHoiQuyenAdmin", usernameParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_TaiKhoan_CapNhatTinhTrang(string uSERNAME, string tINHTRANG)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var tINHTRANGParameter = tINHTRANG != null ?
                new ObjectParameter("TINHTRANG", tINHTRANG) :
                new ObjectParameter("TINHTRANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TaiKhoan_CapNhatTinhTrang", uSERNAMEParameter, tINHTRANGParameter);
        }
    
        public virtual ObjectResult<SP_TaiKhoan_DanhSach_Result> SP_TaiKhoan_DanhSach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TaiKhoan_DanhSach_Result>("SP_TaiKhoan_DanhSach");
        }
    
        public virtual int SP_TaiKhoan_ResetMatKhau(string uSERNAME)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TaiKhoan_ResetMatKhau", uSERNAMEParameter);
        }
    
        public virtual ObjectResult<SP_ThongKe_TrangChu_Result> SP_ThongKe_TrangChu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongKe_TrangChu_Result>("SP_ThongKe_TrangChu");
        }
    
        public virtual int SP_ThongKe_XepLoaiTheoKhoi(string mANAM, string mAHK)
        {
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThongKe_XepLoaiTheoKhoi", mANAMParameter, mAHKParameter);
        }
    
        public virtual ObjectResult<SP_ThongKe_XepLoaiToanTruong_Result> SP_ThongKe_XepLoaiToanTruong(string mANAM, string mAHK)
        {
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongKe_XepLoaiToanTruong_Result>("SP_ThongKe_XepLoaiToanTruong", mANAMParameter, mAHKParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_HS_XemDiemChiTiet_Result> sp_HS_XemDiemChiTiet(string mAHS, string mANAM, string mAHK)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HS_XemDiemChiTiet_Result>("sp_HS_XemDiemChiTiet", mAHSParameter, mANAMParameter, mAHKParameter);
        }
    
        public virtual ObjectResult<sp_HS_XemThoiKhoaBieu_Result> sp_HS_XemThoiKhoaBieu(string mAHS, string mANAM, string mAHK)
        {
            var mAHSParameter = mAHS != null ?
                new ObjectParameter("MAHS", mAHS) :
                new ObjectParameter("MAHS", typeof(string));
    
            var mANAMParameter = mANAM != null ?
                new ObjectParameter("MANAM", mANAM) :
                new ObjectParameter("MANAM", typeof(string));
    
            var mAHKParameter = mAHK != null ?
                new ObjectParameter("MAHK", mAHK) :
                new ObjectParameter("MAHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HS_XemThoiKhoaBieu_Result>("sp_HS_XemThoiKhoaBieu", mAHSParameter, mANAMParameter, mAHKParameter);
        }
    
        public virtual int sp_ThemLop(string mALOP, string tENLOP, string mAKHOI, string mAGVCN)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENLOPParameter = tENLOP != null ?
                new ObjectParameter("TENLOP", tENLOP) :
                new ObjectParameter("TENLOP", typeof(string));
    
            var mAKHOIParameter = mAKHOI != null ?
                new ObjectParameter("MAKHOI", mAKHOI) :
                new ObjectParameter("MAKHOI", typeof(string));
    
            var mAGVCNParameter = mAGVCN != null ?
                new ObjectParameter("MAGVCN", mAGVCN) :
                new ObjectParameter("MAGVCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLop", mALOPParameter, tENLOPParameter, mAKHOIParameter, mAGVCNParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemLop_Result> sp_TimKiemLop(string mALOP, string mAKHOI)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var mAKHOIParameter = mAKHOI != null ?
                new ObjectParameter("MAKHOI", mAKHOI) :
                new ObjectParameter("MAKHOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemLop_Result>("sp_TimKiemLop", mALOPParameter, mAKHOIParameter);
        }
    
        public virtual int sp_SuaLop(string mALOP, string tENLOP, string mAKHOI, string mAGVCN)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            var tENLOPParameter = tENLOP != null ?
                new ObjectParameter("TENLOP", tENLOP) :
                new ObjectParameter("TENLOP", typeof(string));
    
            var mAKHOIParameter = mAKHOI != null ?
                new ObjectParameter("MAKHOI", mAKHOI) :
                new ObjectParameter("MAKHOI", typeof(string));
    
            var mAGVCNParameter = mAGVCN != null ?
                new ObjectParameter("MAGVCN", mAGVCN) :
                new ObjectParameter("MAGVCN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaLop", mALOPParameter, tENLOPParameter, mAKHOIParameter, mAGVCNParameter);
        }
    
        public virtual int sp_XoaLop(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaLop", mALOPParameter);
        }
    }
}
