//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string LOAI { get; set; }
        public string MAGV { get; set; }
        public string MAHS { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> LANDANGNHAPCUOI { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
    }
}
