//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GV_ThongTinVaLopCN
    {
        public string HOTEN { get; set; }
        public string MAGV { get; set; }
        public string LOP_CHUNHIEM { get; set; }
        public string TENLOP { get; set; }
    }
}
