//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GV_TKB
    {
        public string MALOP { get; set; }
        public string MAMH { get; set; }
        public string MAGV { get; set; }
        public string MANAM { get; set; }
        public string MAHK { get; set; }
        public int THU { get; set; }
        public int TIET { get; set; }
        public string MAPHONG { get; set; }
        public string TENMH { get; set; }
        public string TENLOP { get; set; }
        public string TENPHONG { get; set; }
    }
}
