//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HS_XemTKB
    {
        public int THU { get; set; }
        public int TIET { get; set; }
        public string TENMH { get; set; }
        public string GIAOVIEN { get; set; }
        public string TENPHONG { get; set; }
    }
}
