//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HS_BangDiem
    {
        public string MAHK { get; set; }
        public string TENMH { get; set; }
        public string TENLOAIDIEM { get; set; }
        public Nullable<decimal> DIEM { get; set; }
    }
}
