//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTruongCap3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HS_TrangChu
    {
        public string MAHS { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string DANTOC { get; set; }
        public string TONGIAO { get; set; }
        public string NOISINH { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYNHAPHOC { get; set; }
        public string TENLOP { get; set; }
        public string GVCN { get; set; }
    }
}
